/**
 * Antigravity provider.
 * Compiles to .antigravity/instructions.md and .agent/skills/*.md.
 *
 * Antigravity uses Claude Sonnet/Opus models and supports the universal
 * SKILL.md format under .agent/skills/ (workspace) and ~/.gemini/antigravity/skills/ (global).
 * Skills are shareable across 9+ AI coding tools.
 */

import { join } from 'node:path';
import { readFileSafe } from '../utils/fs.js';
import { formatForModel } from '../core/compiler.js';

export const name = 'Antigravity';
export const slug = 'antigravity';
export const files = ['.antigravity/instructions.md', '.agent/skills/'];

export function compile(projectRoot, config, rules, skills, profile) {
  const outputs = [];
  const modelHint = config.providers?.antigravity?.model || 'claude-sonnet-4';

  const ruleItems = rules.map(r => ({
    content: r.content,
    category: r.category || 'rules',
    confidence: r.confidence || 0.5,
  }));

  if (profile?.style) {
    if (profile.style.tone) ruleItems.push({ content: `Tone: ${profile.style.tone}`, category: 'style', confidence: 0.8 });
    if (profile.style.verbosity) ruleItems.push({ content: `Verbosity: ${profile.style.verbosity}`, category: 'style', confidence: 0.8 });
    if (profile.style.comments) ruleItems.push({ content: `Comments: ${profile.style.comments}`, category: 'style', confidence: 0.8 });
  }

  if (config.project?.name) ruleItems.push({ content: `Project: ${config.project.name}`, category: 'context', confidence: 1.0 });
  if (config.project?.language) ruleItems.push({ content: `Language: ${config.project.language}`, category: 'context', confidence: 1.0 });
  if (config.project?.framework) ruleItems.push({ content: `Framework: ${config.project.framework}`, category: 'context', confidence: 1.0 });

  if (profile?.patterns?.length > 0) {
    for (const pattern of profile.patterns) {
      ruleItems.push({ content: pattern, category: 'learned-patterns', confidence: 0.9 });
    }
  }

  const sections = [];
  sections.push('# Antigravity Instructions\n');
  sections.push('> Auto-generated by cortex. Edit .cortex/ sources instead.\n');

  if (ruleItems.length > 0) {
    sections.push(formatForModel(ruleItems, modelHint));
  }

  // Inline skills into main instructions
  if (skills.length > 0) {
    sections.push('\n## Skills\n');
    for (const skill of skills) {
      sections.push(`### ${skill.name}\n`);
      sections.push(skill.content);
      sections.push('');
    }
  }

  outputs.push({
    path: join(projectRoot, '.antigravity', 'instructions.md'),
    content: sections.join('\n'),
  });

  // Also emit skills as individual .agent/skills/*.md files (universal SKILL.md format)
  for (const skill of skills) {
    const skillContent = [
      `# ${skill.name}`,
      '',
      skill.content,
    ].join('\n');

    outputs.push({
      path: join(projectRoot, '.agent', 'skills', `${skill.name}.md`),
      content: skillContent,
    });
  }

  return outputs;
}

export function detect(projectRoot) {
  return readFileSafe(join(projectRoot, '.antigravity', 'instructions.md')) !== null;
}
