// ─────────────────────────────────────────────────────────────────────────────
// Cortex — Universal AI Context Engine
// Copyright (c) 2026 Phani Marupaka. All rights reserved.
// Created & Developed by Phani Marupaka (https://linkedin.com/in/phani-marupaka)
// Licensed under MIT — see LICENSE for terms. Attribution required.
// ─────────────────────────────────────────────────────────────────────────────
/**
 * Claude Code provider.
 * Compiles to CLAUDE.md, .claude/settings.json, and .claude/commands/*.md.
 *
 * Claude responds best to XML-structured, direct imperative instructions.
 * CLAUDE.md is always loaded into context — no size limit but token budget matters.
 * Supports hierarchical CLAUDE.md (parent dirs), sub-agents, hooks, custom slash commands,
 * GitHub Actions integration, and parallel sessions via git worktrees.
 */

import { join } from 'node:path';
import { readFileSafe } from '../utils/fs.js';
import { formatForModel } from '../core/compiler.js';

export const name = 'Claude Code';
export const slug = 'claude';
export const files = ['CLAUDE.md', '.claude/settings.json', '.claude/commands/'];

export function compile(projectRoot, config, rules, skills, profile) {
  const outputs = [];

  // Build CLAUDE.md using model-aware formatting
  const sections = [];
  sections.push('# CLAUDE.md — Project Intelligence\n');
  sections.push('> Auto-generated by [Cortex](https://github.com/Phani3108/Cortex) — Created by [Phani Marupaka](https://linkedin.com/in/phani-marupaka). Edit .cortex/ sources instead.\n');

  // Use the compiler to format rules for Claude's model family
  const ruleItems = rules.map(r => ({
    content: r.content,
    category: r.category || 'rules',
    confidence: r.confidence || 0.5,
  }));

  // Add profile-based items
  if (profile?.style) {
    if (profile.style.tone) ruleItems.push({ content: `Tone: ${profile.style.tone}`, category: 'style', confidence: 0.8 });
    if (profile.style.verbosity) ruleItems.push({ content: `Verbosity: ${profile.style.verbosity}`, category: 'style', confidence: 0.8 });
    if (profile.style.comments) ruleItems.push({ content: `Comments: ${profile.style.comments}`, category: 'style', confidence: 0.8 });
  }

  // Add project info
  if (config.project?.name) ruleItems.push({ content: `Project: ${config.project.name}`, category: 'context', confidence: 1.0 });
  if (config.project?.language) ruleItems.push({ content: `Language: ${config.project.language}`, category: 'context', confidence: 1.0 });
  if (config.project?.framework) ruleItems.push({ content: `Framework: ${config.project.framework}`, category: 'context', confidence: 1.0 });

  // Add learned patterns
  if (profile?.patterns?.length > 0) {
    for (const pattern of profile.patterns) {
      ruleItems.push({ content: pattern, category: 'learned-patterns', confidence: 0.9 });
    }
  }

  if (ruleItems.length > 0) {
    sections.push(formatForModel(ruleItems, 'claude-sonnet-4'));
  }

  // Skills (rendered directly, not through compiler — they're already formatted)
  if (skills.length > 0) {
    sections.push('\n## Skills\n');
    for (const skill of skills) {
      sections.push(`### ${skill.name}\n`);
      sections.push(skill.content);
      sections.push('');
    }
  }

  outputs.push({
    path: join(projectRoot, 'CLAUDE.md'),
    content: sections.join('\n'),
  });

  // .claude/settings.json (local settings)
  const settings = {
    permissions: {},
    memory: { enabled: true },
  };

  if (config.context?.exclude) {
    settings.ignorePaths = config.context.exclude.map(p => p.replace(/\/$/, ''));
  }

  outputs.push({
    path: join(projectRoot, '.claude', 'settings.json'),
    content: JSON.stringify(settings, null, 2) + '\n',
  });

  // .claude/commands/*.md (custom slash commands from skills)
  for (const skill of skills) {
    // Each skill becomes a slash command: /project:skill-name
    const commandContent = [
      `# ${skill.name}`,
      '',
      skill.content,
    ].join('\n');

    outputs.push({
      path: join(projectRoot, '.claude', 'commands', `${skill.name}.md`),
      content: commandContent,
    });
  }

  return outputs;
}

export function detect(projectRoot) {
  return readFileSafe(join(projectRoot, 'CLAUDE.md')) !== null;
}
