// ─────────────────────────────────────────────────────────────────────────────
// Cortex — Universal AI Context Engine
// Copyright (c) 2026 Phani Marupaka. All rights reserved.
// Created & Developed by Phani Marupaka (https://linkedin.com/in/phani-marupaka)
// Licensed under MIT — see LICENSE for terms. Attribution required.
// ─────────────────────────────────────────────────────────────────────────────
/**
 * OpenAI Codex CLI provider.
 * Compiles to AGENTS.md at project root.
 *
 * Codex CLI reads AGENTS.md for project-level agent instructions.
 * Uses o3, o4-mini, and gpt-4o models.
 */

import { join } from 'node:path';
import { readFileSafe } from '../utils/fs.js';
import { formatForModel } from '../core/compiler.js';

export const name = 'OpenAI Codex CLI';
export const slug = 'codex';
export const files = ['AGENTS.md'];

export function compile(projectRoot, config, rules, skills, profile) {
  const outputs = [];
  const modelHint = config.providers?.codex?.model || 'o3';

  const ruleItems = rules.map(r => ({
    content: r.content,
    category: r.category || 'rules',
    confidence: r.confidence || 0.5,
  }));

  if (profile?.style) {
    if (profile.style.tone) ruleItems.push({ content: `Tone: ${profile.style.tone}`, category: 'style', confidence: 0.8 });
    if (profile.style.verbosity) ruleItems.push({ content: `Verbosity: ${profile.style.verbosity}`, category: 'style', confidence: 0.8 });
  }

  if (config.project?.name) ruleItems.push({ content: `Project: ${config.project.name}`, category: 'context', confidence: 1.0 });
  if (config.project?.language) ruleItems.push({ content: `Language: ${config.project.language}`, category: 'context', confidence: 1.0 });
  if (config.project?.framework) ruleItems.push({ content: `Framework: ${config.project.framework}`, category: 'context', confidence: 1.0 });

  if (profile?.patterns?.length > 0) {
    for (const pattern of profile.patterns) {
      ruleItems.push({ content: pattern, category: 'learned-patterns', confidence: 0.9 });
    }
  }

  const sections = [];
  sections.push('# AGENTS.md — Project Intelligence\n');
  sections.push('> Auto-generated by [Cortex](https://github.com/Phani3108/Cortex) — Created by [Phani Marupaka](https://linkedin.com/in/phani-marupaka). Edit .cortex/ sources instead.\n');

  if (ruleItems.length > 0) {
    sections.push(formatForModel(ruleItems, modelHint));
  }

  if (skills.length > 0) {
    for (const skill of skills) {
      sections.push(`\n## ${skill.name}\n`);
      sections.push(skill.content);
    }
  }

  outputs.push({
    path: join(projectRoot, 'AGENTS.md'),
    content: sections.join('\n'),
  });

  return outputs;
}

export function detect(projectRoot) {
  return readFileSafe(join(projectRoot, 'AGENTS.md')) !== null;
}
