/**
 * GitHub Copilot provider.
 * Compiles to .github/copilot-instructions.md.
 *
 * Copilot Chat supports custom instructions via this file.
 * Copilot primarily uses GPT-4o and Claude Sonnet.
 * Has an ~8000 character limit on instructions.
 */

import { join } from 'node:path';
import { readFileSafe } from '../utils/fs.js';
import { formatForModel } from '../core/compiler.js';

export const name = 'GitHub Copilot';
export const slug = 'copilot';
export const files = ['.github/copilot-instructions.md'];

export function compile(projectRoot, config, rules, skills, profile) {
  const outputs = [];

  // Copilot uses GPT-4o by default, but Claude is available
  const modelHint = config.providers?.copilot?.model || 'gpt-4o';

  const ruleItems = rules.map(r => ({
    content: r.content,
    category: r.category || 'rules',
    confidence: r.confidence || 0.5,
  }));

  if (profile?.style) {
    if (profile.style.tone) ruleItems.push({ content: `Be ${profile.style.tone} in explanations`, category: 'style', confidence: 0.8 });
    if (profile.style.comments === 'minimal') ruleItems.push({ content: 'Only add comments where the logic is not self-evident', category: 'style', confidence: 0.8 });
  }

  if (config.project?.language) {
    ruleItems.push({ content: `This is a ${config.project.language} project${config.project.framework ? ` using ${config.project.framework}` : ''}.`, category: 'context', confidence: 1.0 });
  }

  const sections = [];
  sections.push('# Copilot Instructions\n');
  sections.push('> Auto-generated by cortex. Edit .cortex/ sources instead.\n');

  if (ruleItems.length > 0) {
    sections.push(formatForModel(ruleItems, modelHint, { maxTokens: 2000 }));
  }

  if (skills.length > 0) {
    for (const skill of skills) {
      sections.push(`\n## ${skill.name}\n`);
      sections.push(skill.content);
    }
  }

  outputs.push({
    path: join(projectRoot, '.github', 'copilot-instructions.md'),
    content: sections.join('\n'),
  });

  return outputs;
}

export function detect(projectRoot) {
  return readFileSafe(join(projectRoot, '.github', 'copilot-instructions.md')) !== null;
}
