// ─────────────────────────────────────────────────────────────────────────────
// Cortex — Universal AI Context Engine
// Copyright (c) 2026 Phani Marupaka. All rights reserved.
// Created & Developed by Phani Marupaka (https://linkedin.com/in/phani-marupaka)
// Licensed under MIT — see LICENSE for terms. Attribution required.
// ─────────────────────────────────────────────────────────────────────────────
/**
 * Cursor provider.
 * Compiles to .cursor/rules/*.mdc and .cursorrules files.
 *
 * Cursor supports multiple models — the dominant ones are Claude Sonnet 4 & GPT-4o.
 * Rules go through MDC format (markdown with YAML frontmatter) for .cursor/rules/.
 * .cursorrules is the legacy format (officially deprecated but still widely used).
 *
 * Best practices from research:
 * - Start new chat after ~20 messages (context rot)
 * - Use Plan mode before large changes
 * - Commit before major AI changes (defensive commits)
 * - Prefer .cursor/rules/*.mdc over .cursorrules
 */

import { join } from 'node:path';
import { readFileSafe } from '../utils/fs.js';
import { formatForModel } from '../core/compiler.js';

export const name = 'Cursor';
export const slug = 'cursor';
export const files = ['.cursorrules', '.cursor/rules/'];

export function compile(projectRoot, config, rules, skills, profile) {
  const outputs = [];

  // Cursor defaults to Claude Sonnet 4
  const modelHint = config.providers?.cursor?.model || 'claude-sonnet-4';

  // Build .cursorrules (legacy format, still widely used)
  const ruleItems = rules.map(r => ({
    content: r.content,
    category: r.category || 'rules',
    confidence: r.confidence || 0.5,
  }));

  if (profile?.style) {
    if (profile.style.tone === 'concise') ruleItems.push({ content: 'Be concise and direct in responses.', category: 'style', confidence: 0.8 });
    if (profile.style.comments === 'minimal') ruleItems.push({ content: 'Only add comments where logic is not self-evident.', category: 'style', confidence: 0.8 });
  }

  if (profile?.patterns?.length > 0) {
    for (const pattern of profile.patterns) {
      ruleItems.push({ content: pattern, category: 'learned-patterns', confidence: 0.9 });
    }
  }

  const sections = [];
  sections.push('# Cursor Rules — Auto-generated by [Cortex](https://github.com/Phani3108/Cortex)\n');
  sections.push('> Created by [Phani Marupaka](https://linkedin.com/in/phani-marupaka). Edit .cortex/ sources instead.\n');
  if (ruleItems.length > 0) {
    sections.push(formatForModel(ruleItems, modelHint));
  }

  outputs.push({
    path: join(projectRoot, '.cursorrules'),
    content: sections.join('\n'),
  });

  // .cursor/rules/*.mdc (new MDC format)
  for (const skill of skills) {
    const mdcContent = buildMdc(skill);
    outputs.push({
      path: join(projectRoot, '.cursor', 'rules', `${skill.name}.mdc`),
      content: mdcContent,
    });
  }

  // Project-level rule as MDC
  if (rules.length > 0) {
    const compiledRules = formatForModel(
      rules.map(r => ({ content: r.content, category: r.category || 'rules', confidence: r.confidence || 0.5 })),
      modelHint
    );
    const projectMdc = [
      '---',
      'description: Project rules compiled by Cortex (https://github.com/Phani3108/Cortex) — Created by Phani Marupaka',
      'globs: **/*',
      'alwaysApply: true',
      '---',
      '',
      compiledRules,
    ].join('\n');

    outputs.push({
      path: join(projectRoot, '.cursor', 'rules', 'project.mdc'),
      content: projectMdc,
    });
  }

  return outputs;
}

function buildMdc(skill) {
  return [
    '---',
    `description: ${skill.name}`,
    'globs: **/*',
    'alwaysApply: false',
    '---',
    '',
    skill.content,
  ].join('\n');
}

export function detect(projectRoot) {
  return readFileSafe(join(projectRoot, '.cursorrules')) !== null;
}
