/**
 * Google Gemini CLI + Code Assist provider.
 * Compiles to GEMINI.md (CLI), .gemini/style-guide.md (Code Assist), and .gemini/settings.json.
 *
 * Gemini CLI reads GEMINI.md from project root (+ hierarchical parent dirs + ~/.gemini/GEMINI.md).
 * Gemini Code Assist (IDE plugin) reads .gemini/style-guide.md.
 * Gemini has a massive context window (2M+ tokens) so we can be verbose.
 *
 * Supports: /memory, /compress, custom slash commands (TOML), extensions (MCP),
 * checkpointing, sandbox, multi-directory, YOLO mode.
 */

import { join } from 'node:path';
import { readFileSafe } from '../utils/fs.js';
import { formatForModel } from '../core/compiler.js';

export const name = 'Gemini CLI';
export const slug = 'gemini';
export const files = ['GEMINI.md', '.gemini/style-guide.md', '.gemini/settings.json'];

export function compile(projectRoot, config, rules, skills, profile) {
  const outputs = [];
  const modelHint = config.providers?.gemini?.model || 'gemini-2.5-pro';

  const ruleItems = rules.map(r => ({
    content: r.content,
    category: r.category || 'rules',
    confidence: r.confidence || 0.5,
  }));

  if (profile?.style) {
    if (profile.style.tone) ruleItems.push({ content: `Tone: ${profile.style.tone}`, category: 'style', confidence: 0.8 });
    if (profile.style.verbosity) ruleItems.push({ content: `Detail level: ${profile.style.verbosity}`, category: 'style', confidence: 0.8 });
  }

  if (config.project?.name) ruleItems.push({ content: `Project: ${config.project.name}`, category: 'context', confidence: 1.0 });
  if (config.project?.language) ruleItems.push({ content: `Language: ${config.project.language}`, category: 'context', confidence: 1.0 });
  if (config.project?.framework) ruleItems.push({ content: `Framework: ${config.project.framework}`, category: 'context', confidence: 1.0 });

  // ── GEMINI.md (primary — for Gemini CLI) ──────────────────────────────────
  const cliSections = [];
  cliSections.push('# GEMINI.md — Project Intelligence\n');
  cliSections.push('> Auto-generated by cortex. Edit .cortex/ sources instead.\n');

  if (ruleItems.length > 0) {
    cliSections.push(formatForModel(ruleItems, modelHint));
  }

  if (skills.length > 0) {
    cliSections.push('\n## Skills\n');
    for (const skill of skills) {
      cliSections.push(`### ${skill.name}\n`);
      cliSections.push(skill.content);
      cliSections.push('');
    }
  }

  outputs.push({
    path: join(projectRoot, 'GEMINI.md'),
    content: cliSections.join('\n'),
  });

  // ── .gemini/style-guide.md (for Gemini Code Assist IDE plugin) ────────────
  const assistSections = [];
  assistSections.push('# Gemini Style Guide\n');
  assistSections.push('> Auto-generated by cortex. Edit .cortex/ sources instead.\n');

  if (ruleItems.length > 0) {
    assistSections.push(formatForModel(ruleItems, modelHint));
  }

  if (skills.length > 0) {
    for (const skill of skills) {
      assistSections.push(`\n## ${skill.name}\n`);
      assistSections.push(skill.content);
    }
  }

  outputs.push({
    path: join(projectRoot, '.gemini', 'style-guide.md'),
    content: assistSections.join('\n'),
  });

  // ── .gemini/settings.json ─────────────────────────────────────────────────
  const settings = {
    codeStyle: {
      language: config.project?.language || 'auto',
    },
    sandbox: true,
  };

  if (config.context?.exclude) {
    settings.ignorePaths = config.context.exclude;
  }

  outputs.push({
    path: join(projectRoot, '.gemini', 'settings.json'),
    content: JSON.stringify(settings, null, 2) + '\n',
  });

  return outputs;
}

export function detect(projectRoot) {
  return (
    readFileSafe(join(projectRoot, 'GEMINI.md')) !== null ||
    readFileSafe(join(projectRoot, '.gemini', 'style-guide.md')) !== null
  );
}
