// ─────────────────────────────────────────────────────────────────────────────
// Cortex — Universal AI Context Engine
// Copyright (c) 2026 Phani Marupaka. All rights reserved.
// Created & Developed by Phani Marupaka (https://linkedin.com/in/phani-marupaka)
// Licensed under MIT — see LICENSE for terms. Attribution required.
// ─────────────────────────────────────────────────────────────────────────────
/**
 * Amazon Kiro provider.
 * Compiles to .kiro/rules/*.md (always-on and on-demand rules)
 * and .kiro/specs/ structure (requirements.md → design.md → tasks.md).
 *
 * Kiro is a spec-driven IDE that converts vibe prompts into formal specifications.
 * It supports steering hooks (event-driven automation) and agent hooks (pre/post).
 * Rules use YAML frontmatter for trigger configuration.
 */

import { join } from 'node:path';
import { readFileSafe } from '../utils/fs.js';
import { formatForModel } from '../core/compiler.js';

export const name = 'Amazon Kiro';
export const slug = 'kiro';
export const files = ['.kiro/rules/', '.kiro/specs/'];

export function compile(projectRoot, config, rules, skills, profile) {
  const outputs = [];
  const modelHint = config.providers?.kiro?.model || 'claude-sonnet-4';

  const ruleItems = rules.map(r => ({
    content: r.content,
    category: r.category || 'rules',
    confidence: r.confidence || 0.5,
  }));

  if (profile?.style) {
    if (profile.style.tone) ruleItems.push({ content: `Tone: ${profile.style.tone}`, category: 'style', confidence: 0.8 });
    if (profile.style.verbosity) ruleItems.push({ content: `Verbosity: ${profile.style.verbosity}`, category: 'style', confidence: 0.8 });
    if (profile.style.comments) ruleItems.push({ content: `Comments: ${profile.style.comments}`, category: 'style', confidence: 0.8 });
  }

  if (config.project?.name) ruleItems.push({ content: `Project: ${config.project.name}`, category: 'context', confidence: 1.0 });
  if (config.project?.language) ruleItems.push({ content: `Language: ${config.project.language}`, category: 'context', confidence: 1.0 });
  if (config.project?.framework) ruleItems.push({ content: `Framework: ${config.project.framework}`, category: 'context', confidence: 1.0 });

  // ── Always-on project rule ────────────────────────────────────────────────
  const compiledRules = ruleItems.length > 0 ? formatForModel(ruleItems, modelHint) : '';

  const projectRule = [
    '---',
    'trigger: always_on',
    '---',
    '',
    '# Project Rules',
    '',
    '> Auto-generated by [Cortex](https://github.com/Phani3108/Cortex) — Created by [Phani Marupaka](https://linkedin.com/in/phani-marupaka). Edit .cortex/ sources instead.',
    '',
    compiledRules,
  ].join('\n');

  outputs.push({
    path: join(projectRoot, '.kiro', 'rules', 'project.md'),
    content: projectRule,
  });

  // ── Skills as on-demand rules ─────────────────────────────────────────────
  for (const skill of skills) {
    const skillRule = [
      '---',
      'trigger: on_demand',
      '---',
      '',
      `# ${skill.name}`,
      '',
      skill.content,
    ].join('\n');

    outputs.push({
      path: join(projectRoot, '.kiro', 'rules', `${skill.name}.md`),
      content: skillRule,
    });
  }

  return outputs;
}

export function detect(projectRoot) {
  return readFileSafe(join(projectRoot, '.kiro', 'rules', 'project.md')) !== null;
}
