/**
 * OpenAI ChatGPT / custom instructions provider.
 * Compiles to .openai/instructions.md.
 *
 * This file can be referenced in ChatGPT custom instructions or
 * used by OpenAI-powered IDE integrations. Uses numbered list format
 * optimized for GPT-family models.
 */

import { join } from 'node:path';
import { readFileSafe } from '../utils/fs.js';
import { formatForModel } from '../core/compiler.js';

export const name = 'OpenAI';
export const slug = 'openai';
export const files = ['.openai/instructions.md'];

export function compile(projectRoot, config, rules, skills, profile) {
  const outputs = [];
  const modelHint = config.providers?.openai?.model || 'gpt-4o';

  const ruleItems = rules.map(r => ({
    content: r.content,
    category: r.category || 'rules',
    confidence: r.confidence || 0.5,
  }));

  if (profile?.style) {
    if (profile.style.tone) ruleItems.push({ content: `Respond in a ${profile.style.tone} manner.`, category: 'style', confidence: 0.8 });
    if (profile.style.comments === 'minimal') ruleItems.push({ content: 'Use minimal comments — only where logic is not self-evident.', category: 'style', confidence: 0.8 });
  }

  if (config.project?.name) ruleItems.push({ content: `Working on: ${config.project.name}`, category: 'context', confidence: 1.0 });
  if (config.project?.language) ruleItems.push({ content: `Language: ${config.project.language}`, category: 'context', confidence: 1.0 });
  if (config.project?.framework) ruleItems.push({ content: `Framework: ${config.project.framework}`, category: 'context', confidence: 1.0 });

  const sections = [];
  sections.push('# OpenAI Custom Instructions\n');
  sections.push('> Auto-generated by cortex. Edit .cortex/ sources instead.\n');

  if (ruleItems.length > 0) {
    sections.push(formatForModel(ruleItems, modelHint));
  }

  if (skills.length > 0) {
    for (const skill of skills) {
      sections.push(`\n## ${skill.name}\n`);
      sections.push(skill.content);
    }
  }

  outputs.push({
    path: join(projectRoot, '.openai', 'instructions.md'),
    content: sections.join('\n'),
  });

  return outputs;
}

export function detect(projectRoot) {
  return readFileSafe(join(projectRoot, '.openai', 'instructions.md')) !== null;
}
