/**
 * Windsurf (Codeium) provider.
 * Compiles to .windsurfrules at project root.
 *
 * Windsurf's Cascade reads .windsurfrules — similar to .cursorrules.
 * Supports Claude, GPT-4o, and Windsurf-internal models.
 */

import { join } from 'node:path';
import { readFileSafe } from '../utils/fs.js';
import { formatForModel } from '../core/compiler.js';

export const name = 'Windsurf';
export const slug = 'windsurf';
export const files = ['.windsurfrules'];

export function compile(projectRoot, config, rules, skills, profile) {
  const outputs = [];
  const modelHint = config.providers?.windsurf?.model || 'claude-sonnet-4';

  const ruleItems = rules.map(r => ({
    content: r.content,
    category: r.category || 'rules',
    confidence: r.confidence || 0.5,
  }));

  if (profile?.style) {
    if (profile.style.tone === 'concise') ruleItems.push({ content: 'Be concise and direct in responses.', category: 'style', confidence: 0.8 });
    if (profile.style.comments === 'minimal') ruleItems.push({ content: 'Only add comments where logic is not self-evident.', category: 'style', confidence: 0.8 });
  }

  if (config.project?.name) ruleItems.push({ content: `Project: ${config.project.name}`, category: 'context', confidence: 1.0 });
  if (config.project?.language) ruleItems.push({ content: `Language: ${config.project.language}`, category: 'context', confidence: 1.0 });
  if (config.project?.framework) ruleItems.push({ content: `Framework: ${config.project.framework}`, category: 'context', confidence: 1.0 });

  if (profile?.patterns?.length > 0) {
    for (const pattern of profile.patterns) {
      ruleItems.push({ content: pattern, category: 'learned-patterns', confidence: 0.9 });
    }
  }

  const sections = [];
  sections.push('# Windsurf Rules — Auto-generated by cortex\n');

  if (ruleItems.length > 0) {
    sections.push(formatForModel(ruleItems, modelHint, { maxTokens: 6000 }));
  }

  if (skills.length > 0) {
    for (const skill of skills) {
      sections.push(`\n## ${skill.name}\n`);
      sections.push(skill.content);
    }
  }

  outputs.push({
    path: join(projectRoot, '.windsurfrules'),
    content: sections.join('\n'),
  });

  return outputs;
}

export function detect(projectRoot) {
  return readFileSafe(join(projectRoot, '.windsurfrules')) !== null;
}
