// ─────────────────────────────────────────────────────────────────────────────
// Cortex — Universal AI Context Engine
// Copyright (c) 2026 Phani Marupaka. All rights reserved.
// Licensed under MIT — see LICENSE for terms. Attribution required.
// ─────────────────────────────────────────────────────────────────────────────
/**
 * The compiler. Pure function: sources in, files out.
 *
 *   .cortex/rules/*.md  ─┐
 *   .cortex/skills/*.md ─┼─▶ compile() ─▶ [{ path, content, target, … }] + report
 *   config              ─┘
 *
 * The CLI writes the result to disk (ownership-safe); the website renders it
 * in the playground. Both run this exact code, so the site never lies.
 */

import { TARGETS, resolveTargetId, SHARED_SKILLS_DIR } from './targets.js';
import { parseRuleFile, parseSkillFile, dedupeRules, slugify } from './rules.js';
import { formatRules, styleForFormatFamily } from './format.js';
import { fitRules } from './budget.js';
import { measure, tokenizerFor, estimateTokens } from './tokens.js';
import { getFormatFamily, resolveModel } from '../core/families.js';

export const MARKER = 'Generated by Cortex';
export const HOMEPAGE = 'https://github.com/Phani3108/Cortex';
const MARKER_LINE = `<!-- ${MARKER} (${HOMEPAGE}) from .cortex/ — edit the sources there, then run \`cortex compile\`. Created by Phani Marupaka. -->`;

/** True when a file's content was produced by Cortex (current or legacy marker). */
export function isGenerated(content) {
  return typeof content === 'string' && (content.includes(MARKER) || content.includes('Auto-generated by [Cortex]'));
}

/**
 * Normalise config.providers into { id: { enabled, model } }.
 * Accepts booleans, { enabled, model } objects and aliases.
 */
export function normalizeTargets(providers = {}) {
  const out = {};
  const unknown = [];
  for (const [key, value] of Object.entries(providers || {})) {
    const id = resolveTargetId(key);
    if (!id) { unknown.push(key); continue; }
    if (value === true || value === 'true') out[id] = { enabled: true, model: null };
    else if (value && typeof value === 'object') {
      out[id] = { enabled: value.enabled !== false, model: value.model || null };
    } else out[id] = { enabled: false, model: null };
  }
  return { targets: out, unknown };
}

/**
 * Compile sources for every enabled target.
 *
 * @param {object} input
 * @param {Array<{path:string, content:string}>} input.ruleFiles
 * @param {Array<{path:string, content:string}>} [input.skillFiles]
 * @param {object} input.config         - parsed .cortex/config.yaml
 * @param {Array}  [input.extraRules]   - e.g. personal style from ~/.cortex/profile.yaml
 * @param {string[]} [input.only]       - restrict to these target ids
 * @returns {{ outputs: Array, report: object, rules: Array, skills: Array, warnings: string[] }}
 */
export function compile(input) {
  const config = input.config || {};
  const warnings = [];

  // ── Parse sources ──────────────────────────────────────────────────────────
  const parsed = [];
  for (const file of input.ruleFiles || []) {
    const { meta, rules } = parseRuleFile(file.content, file.path);
    parsed.push({ file: file.path, meta, rules });
  }
  let allRules = dedupeRules([...parsed.flatMap(p => p.rules), ...(input.extraRules || [])]);
  const unscoped = allRules.filter(r => !r.scope);
  const scopedGroups = groupScoped(allRules.filter(r => r.scope), parsed);

  const skills = [];
  const seenSkills = new Set();
  for (const file of input.skillFiles || []) {
    const skill = parseSkillFile(file.content, file.path);
    if (seenSkills.has(skill.name)) { warnings.push(`Duplicate skill name "${skill.name}" in ${file.path} — skipped.`); continue; }
    seenSkills.add(skill.name);
    skills.push(skill);
  }

  // ── Resolve targets ────────────────────────────────────────────────────────
  const { targets, unknown } = normalizeTargets(config.providers);
  for (const u of unknown) warnings.push(`Unknown provider "${u}" in config.yaml — ignored. Known: ${Object.keys(TARGETS).join(', ')}.`);
  let enabled = Object.entries(targets).filter(([, t]) => t.enabled).map(([id]) => id);
  if (input.only?.length) enabled = enabled.filter(id => input.only.includes(id));

  const agentsMode = config.output?.agentsMd === 'duplicate' ? 'duplicate' : 'shared';
  // Delegation depends on config, not on `-p` filtering, so partial compiles match full ones.
  const agentsMdOn = targets.codex?.enabled === true;
  const project = config.project || {};
  const outputs = [];
  const report = {};

  for (const id of enabled) {
    const target = TARGETS[id];
    const model = targets[id]?.model || null;
    const style = model ? styleForFormatFamily(getFormatFamily(model)) : target.style;
    const tokenizer = tokenizerFor(model ? resolveModel(model).family : familyForStyle(style));
    const entry = report[id] = { id, name: target.name, style, model, files: [], dropped: [], warnings: [], viaAgentsMd: false };

    // 1. Always-on instructions
    const delegate = agentsMode === 'shared' && agentsMdOn && id !== 'codex' && target.readsAgentsMd;
    if (delegate) {
      entry.viaAgentsMd = true;
    } else {
      const inlineScoped = target.scopedPattern ? [] : scopedGroups;
      const render = kept => renderMain(target, { rules: kept, scoped: inlineScoped, style, project });
      const budget = target.budget.hard ? { unit: target.budget.unit, limit: target.budget.hard } : null;
      const flat = [...unscoped, ...inlineScoped.flatMap(g => g.rules)];
      let kept = unscoped;
      let content;
      if (budget) {
        const fit = fitRules(flat, budget, list => render(list.filter(r => !r.scope)) + renderScopedSections(inlineScoped, list, style), tokenizer);
        kept = fit.kept;
        entry.dropped.push(...fit.dropped);
        content = render(kept.filter(r => !r.scope)) + renderScopedSections(inlineScoped, kept, style);
        if (!fit.fits) entry.warnings.push(`Even the highest-priority rules exceed ${target.budget.hard} ${target.budget.unit}.`);
      } else {
        content = render(unscoped) + renderScopedSections(inlineScoped, flat, style);
      }
      outputs.push(makeOutput(target.mainFile, content, id, 'instructions', target, tokenizer));
    }

    // 2. Path-scoped rules → native scoped files
    if (target.scopedPattern) {
      for (const group of scopedGroups) {
        const path = target.scopedPattern.replace('{slug}', group.slug);
        const content = renderScoped(target, group, style);
        outputs.push(makeOutput(path, content, id, 'scoped', target, tokenizer));
      }
    }

    // 3. Skills → Agent Skills (SKILL.md) in the directory this tool reads
    if (target.skillsDir && config.output?.skills !== false) {
      for (const skill of skills) {
        const path = `${target.skillsDir}/${skill.name}/SKILL.md`;
        outputs.push(makeOutput(path, renderSkill(skill), id, 'skill', target, tokenizer));
      }
    }

    // Budget warnings (soft limits)
    for (const out of outputs.filter(o => o.target === id)) {
      entry.files.push(out.path);
      const b = target.budget;
      if (b.soft && out.kind !== 'skill') {
        const size = measure(out.content, b.unit, tokenizer);
        if (size > b.soft) entry.warnings.push(`${out.path} is ${size} ${b.unit} (guidance: ≤ ${b.soft}). ${b.note}`);
      }
    }
    if (entry.dropped.length) {
      const critical = entry.dropped.filter(r => r.priority === 'critical').length;
      entry.warnings.push(`${entry.dropped.length} lower-priority rule(s) left out to fit ${target.budget.hard} ${target.budget.unit}${critical ? ` — including ${critical} critical rule(s)!` : ''}.`);
    }
  }

  return { outputs: mergeShared(outputs, warnings), report, rules: allRules, skills, warnings };
}

// ── Rendering ────────────────────────────────────────────────────────────────

function familyForStyle(style) {
  return { xml: 'anthropic', numbered: 'openai-gpt', reasoning: 'openai-reasoning', gemini: 'gemini', explicit: 'meta-llama' }[style] || 'default';
}

function projectLine(project) {
  const bits = [project.name, project.language, project.framework].filter(Boolean);
  return bits.length ? `Project: ${bits.join(' · ')}` : '';
}

function title(target) {
  switch (target.id) {
    case 'claude': return '# CLAUDE.md';
    case 'codex': return '# AGENTS.md';
    case 'gemini': return '# GEMINI.md';
    case 'gemini-review': return '# Code review style guide';
    case 'openai': return '# Custom instructions';
    default: return '# Project rules';
  }
}

function frontmatter(target, kind, extra = {}) {
  const lines = [];
  switch (target.id) {
    case 'cursor':
      lines.push(`description: ${extra.description || 'Project rules compiled by Cortex'}`);
      lines.push(`globs: ${extra.globs ? extra.globs.join(',') : ''}`.trimEnd());
      lines.push(`alwaysApply: ${kind === 'instructions'}`);
      break;
    case 'windsurf':
    case 'antigravity':
      if (kind === 'instructions') lines.push('trigger: always_on');
      else { lines.push('trigger: glob'); lines.push(`globs: ${extra.globs.join(',')}`); }
      if (extra.description) lines.push(`description: ${extra.description}`);
      break;
    case 'kiro':
      if (kind === 'instructions') lines.push('inclusion: always');
      else { lines.push('inclusion: fileMatch'); lines.push(`fileMatchPattern: ${JSON.stringify(extra.globs.length === 1 ? extra.globs[0] : extra.globs)}`); }
      break;
    case 'copilot':
      if (kind === 'scoped') lines.push(`applyTo: ${JSON.stringify(extra.globs.join(','))}`);
      break;
    case 'claude':
      if (kind === 'scoped') { lines.push('paths:'); for (const g of extra.globs) lines.push(`  - ${JSON.stringify(g)}`); }
      break;
    default:
      break;
  }
  return lines.length ? `---\n${lines.join('\n')}\n---\n` : '';
}

function renderMain(target, { rules, style, project }) {
  const parts = [frontmatter(target, 'instructions') + MARKER_LINE, '', title(target), ''];
  const ctx = projectLine(project);
  if (ctx) parts.push(ctx, '');
  if (target.id === 'openai') parts.push('Apply these rules whenever you help with this project.', '');
  if (rules.length) parts.push(formatRules(rules, style).trimEnd(), '');
  else parts.push('_No rules yet — add them to `.cortex/rules/*.md`._', '');
  return parts.join('\n');
}

function renderScopedSections(groups, keptRules, style) {
  if (!groups.length) return '';
  const keep = new Set(keptRules);
  const parts = [];
  for (const g of groups) {
    const rules = g.rules.filter(r => keep.has(r));
    if (!rules.length) continue;
    parts.push(`\n## When working on ${g.scope.map(s => `\`${s}\``).join(', ')}\n`);
    parts.push(formatRules(rules, style === 'xml' ? 'xml' : 'markdown', { headingLevel: 3 }).trimEnd());
  }
  return parts.length ? parts.join('\n') + '\n' : '';
}

function renderScoped(target, group, style) {
  const fm = frontmatter(target, 'scoped', { globs: group.scope, description: group.description });
  return [fm + MARKER_LINE, '', `# ${group.title}`, '', `Applies to: ${group.scope.map(s => `\`${s}\``).join(', ')}`, '', formatRules(group.rules, style).trimEnd(), ''].join('\n');
}

export function renderSkill(skill) {
  const desc = skill.description.replace(/\s+/g, ' ').trim().slice(0, 1024);
  return [
    '---',
    `name: ${skill.name}`,
    `description: ${JSON.stringify(desc)}`,
    '---',
    MARKER_LINE,
    '',
    skill.body.trim(),
    '',
  ].join('\n');
}

function groupScoped(rules, parsed) {
  const groups = new Map();
  for (const r of rules) {
    const key = r.scope.join(',');
    if (!groups.has(key)) {
      const src = parsed.find(p => p.file === r.source);
      const base = src?.meta?.name || String(r.source || 'scoped').split('/').pop().replace(/\.(md|txt)$/i, '');
      groups.set(key, {
        scope: r.scope,
        slug: slugify(base),
        title: src?.meta?.title || titleFromSlug(base),
        description: src?.meta?.description || `Rules for ${r.scope.join(', ')}`,
        rules: [],
      });
    }
    groups.get(key).rules.push(r);
  }
  // Two files may share a slug with different scopes — disambiguate.
  const used = new Map();
  for (const g of groups.values()) {
    const n = used.get(g.slug) || 0;
    used.set(g.slug, n + 1);
    if (n) g.slug = `${g.slug}-${n + 1}`;
  }
  return [...groups.values()];
}

function titleFromSlug(s) {
  return String(s).replace(/[-_]+/g, ' ').replace(/\b\w/g, c => c.toUpperCase());
}

function makeOutput(path, content, target, kind, def, tokenizer) {
  return {
    path,
    content,
    target,
    kind,
    tokens: estimateTokens(content, tokenizer),
    chars: content.length,
    lines: content.split('\n').length,
    budget: def.budget,
  };
}

/** Several targets may emit the same shared file (e.g. .agents/skills/x/SKILL.md). */
function mergeShared(outputs, warnings) {
  const byPath = new Map();
  for (const o of outputs) {
    const prev = byPath.get(o.path);
    if (!prev) { byPath.set(o.path, { ...o, targets: [o.target] }); continue; }
    if (prev.content !== o.content) warnings.push(`Conflicting content for ${o.path} (${prev.target} vs ${o.target}); kept ${prev.target}.`);
    prev.targets.push(o.target);
  }
  return [...byPath.values()];
}

/** Skill directories written for a set of enabled targets (for docs / status). */
export function skillDirsFor(targetIds) {
  const dirs = new Set();
  for (const id of targetIds) if (TARGETS[id]?.skillsDir) dirs.add(TARGETS[id].skillsDir);
  return [...dirs];
}

export { SHARED_SKILLS_DIR };
