// ─────────────────────────────────────────────────────────────────────────────
// Cortex — Universal AI Context Engine
// Copyright (c) 2026 Phani Marupaka. All rights reserved.
// Created & Developed by Phani Marupaka (https://linkedin.com/in/phani-marupaka)
// Licensed under MIT — see LICENSE for terms. Attribution required.
// ─────────────────────────────────────────────────────────────────────────────
/**
 * cortex import — bring hand-written tool files (CLAUDE.md, AGENTS.md,
 * .cursor/rules/*.mdc, .github/copilot-instructions.md, …) into .cortex/.
 *
 * Files generated by Cortex are skipped, rules already present in .cortex/
 * are de-duplicated, and path scoping (Cursor globs, Copilot applyTo, Kiro
 * fileMatchPattern, Claude paths) is preserved as `scope:` frontmatter.
 */

import { join, basename } from 'node:path';
import { existsSync, readFileSync, readdirSync, statSync, mkdirSync, writeFileSync } from 'node:fs';
import { findProjectRoot, getCortexDir } from '../utils/fs.js';
import { loadRuleFiles } from '../core/sources.js';
import { IMPORTABLE, TARGETS, isGenerated, parseRuleFile, splitFrontmatter, dedupeRules, slugify, parseSkillFile } from '../engine/index.js';
import { heading, info, success, warn, dim } from '../utils/log.js';

export default async function importCmd({ values }) {
  const projectRoot = findProjectRoot();
  const result = importExisting(projectRoot, { dry: values.dry });
  if (values.quiet) return;

  heading('Importing existing AI tool files');
  if (!result.found.length) {
    info('No hand-written instruction files found.');
    dim('Looked for CLAUDE.md, AGENTS.md, GEMINI.md, .cursor/rules, .github/copilot-instructions.md, .windsurf/rules, .kiro/steering, .agents/rules and skills.');
    return;
  }
  for (const f of result.found) {
    if (f.skipped) dim(`${f.file} — ${f.skipped}`);
    else success(`${f.file} → ${f.dest} (${f.count} ${f.kind === 'skill' ? 'skill' : 'rule(s)'})`);
  }
  console.log();
  if (result.imported) {
    success(`${values.dry ? 'Would import' : 'Imported'} ${result.imported} item(s). Review them in .cortex/, then run \`cortex compile --force\` to replace the originals with generated files.`);
  } else {
    info('Nothing new to import — .cortex/ already has these rules.');
  }
}

/**
 * Import all importable files. Shared with `cortex init`.
 * @returns {{ found: Array, imported: number }}
 */
export function importExisting(projectRoot, { dry = false } = {}) {
  const cortexDir = getCortexDir(projectRoot);
  const existing = loadRuleFiles(cortexDir).flatMap(f => parseRuleFile(f.content, f.path).rules);
  const known = new Set(existing.map(r => key(r)));
  const found = [];
  let imported = 0;

  for (const candidate of expandCandidates(projectRoot)) {
    const content = readFileSync(candidate.abs, 'utf-8');
    if (isGenerated(content)) {
      found.push({ file: candidate.file, skipped: 'generated by Cortex, skipped' });
      continue;
    }
    const { meta, body } = splitFrontmatter(content);
    const scope = scopeFromFrontmatter(candidate.target, meta);
    const { rules } = parseRuleFile(body, candidate.file);
    const fresh = dedupeRules(rules).filter(r => !known.has(key({ ...r, scope })));
    if (!fresh.length) {
      found.push({ file: candidate.file, skipped: 'nothing new' });
      continue;
    }
    for (const r of fresh) known.add(key({ ...r, scope }));

    const name = candidate.dir ? `${candidate.target}-${slugify(basename(candidate.file).replace(/(\.instructions)?\.(mdc|md)$/i, ''))}` : candidate.target;
    const dest = uniquePath(join(cortexDir, 'rules'), `imported-${name}`);
    const text = renderImported(candidate, fresh, scope);
    if (!dry) {
      mkdirSync(join(cortexDir, 'rules'), { recursive: true });
      writeFileSync(join(cortexDir, 'rules', dest), text, 'utf-8');
    }
    imported += fresh.length;
    found.push({ file: candidate.file, dest: `.cortex/rules/${dest}`, count: fresh.length, kind: 'rules' });
  }

  // Skills written by hand in any tool's skills dir, and Claude slash commands
  for (const skill of expandSkills(projectRoot)) {
    const content = readFileSync(skill.abs, 'utf-8');
    if (isGenerated(content)) continue;
    const parsed = parseSkillFile(content, skill.name + '.md');
    const destDir = join(cortexDir, 'skills', parsed.name);
    if (existsSync(destDir) || existsSync(join(cortexDir, 'skills', `${parsed.name}.md`))) {
      found.push({ file: skill.file, skipped: 'skill already in .cortex/skills' });
      continue;
    }
    if (!dry) {
      mkdirSync(destDir, { recursive: true });
      writeFileSync(join(destDir, 'SKILL.md'), content, 'utf-8');
    }
    imported++;
    found.push({ file: skill.file, dest: `.cortex/skills/${parsed.name}/SKILL.md`, count: 1, kind: 'skill' });
  }

  return { found, imported };
}

/**
 * Hand-written originals whose every rule already lives in .cortex/ — they now
 * duplicate generated files (e.g. .cursor/rules/testing.mdc after import).
 */
export function findRedundantOriginals(projectRoot, outputPaths, sourceRules) {
  const known = new Set(sourceRules.map(r => key(r)));
  const out = [];
  for (const c of expandCandidates(projectRoot)) {
    if (outputPaths.has(c.file)) continue;
    const content = readFileSync(c.abs, 'utf-8');
    if (isGenerated(content)) continue;
    const { meta, body } = splitFrontmatter(content);
    const scope = scopeFromFrontmatter(c.target, meta);
    const { rules } = parseRuleFile(body, c.file);
    if (rules.length && rules.every(r => known.has(key({ ...r, scope })))) out.push(c.file);
  }
  return out;
}

function key(r) {
  return `${(r.scope || []).join('|')}::${r.text.toLowerCase().replace(/[^a-z0-9]+/g, ' ').trim()}`;
}

function expandCandidates(root) {
  const out = [];
  for (const item of IMPORTABLE) {
    if (item.path) {
      const abs = join(root, item.path);
      if (existsSync(abs) && statSync(abs).isFile()) out.push({ ...item, file: item.path, abs });
      continue;
    }
    const dir = join(root, item.dir);
    if (!existsSync(dir) || !statSync(dir).isDirectory()) continue;
    for (const name of readdirSync(dir).sort()) {
      if (!name.endsWith(item.ext)) continue;
      const abs = join(dir, name);
      if (statSync(abs).isFile()) out.push({ ...item, file: `${item.dir}/${name}`, abs });
    }
  }
  return out;
}

function expandSkills(root) {
  const out = [];
  for (const dir of ['.claude/skills', '.agents/skills', '.kiro/skills', '.github/skills', '.cursor/skills', '.windsurf/skills', '.devin/skills']) {
    const abs = join(root, dir);
    if (!existsSync(abs)) continue;
    for (const name of readdirSync(abs).sort()) {
      const skillMd = join(abs, name, 'SKILL.md');
      if (existsSync(skillMd)) out.push({ abs: skillMd, file: `${dir}/${name}/SKILL.md`, name });
    }
  }
  const commands = join(root, '.claude', 'commands');
  if (existsSync(commands)) {
    for (const name of readdirSync(commands).sort()) {
      if (name.endsWith('.md')) out.push({ abs: join(commands, name), file: `.claude/commands/${name}`, name: name.replace(/\.md$/, '') });
    }
  }
  return out;
}

/** Translate each tool's scoping frontmatter into Cortex `scope:` globs. */
function scopeFromFrontmatter(target, meta = {}) {
  const list = v => (Array.isArray(v) ? v : String(v).split(',')).map(s => String(s).trim()).filter(Boolean);
  if (target === 'cursor' && meta.globs && meta.alwaysApply !== true) return list(meta.globs);
  if (target === 'copilot' && meta.applyTo && meta.applyTo !== '**') return list(meta.applyTo);
  if ((target === 'windsurf' || target === 'antigravity') && meta.trigger === 'glob' && (meta.globs || meta.glob)) return list(meta.globs || meta.glob);
  if (target === 'kiro' && meta.inclusion === 'fileMatch' && meta.fileMatchPattern) return list(meta.fileMatchPattern);
  if (target === 'claude' && meta.paths) return list(meta.paths);
  return null;
}

function renderImported(candidate, rules, scope) {
  const lines = [];
  if (scope) lines.push('---', `scope: ${JSON.stringify(scope)}`, '---');
  lines.push(`# Imported from ${TARGETS[candidate.target]?.name || candidate.target} (${candidate.file})`, '');
  lines.push('<!-- Imported by `cortex import`. Edit freely: this file is now the source of truth. -->', '');
  let category = null;
  for (const r of rules) {
    if (r.category !== category) {
      category = r.category;
      lines.push('', `## ${r.label || r.category}`);
    }
    lines.push(`- ${r.priority === 'critical' ? '! ' : ''}${r.text}`);
  }
  return lines.join('\n').replace(/\n{3,}/g, '\n\n').trim() + '\n';
}

function uniquePath(dir, base) {
  let name = `${base}.md`;
  let i = 2;
  while (existsSync(join(dir, name))) name = `${base}-${i++}.md`;
  return name;
}
