// ─────────────────────────────────────────────────────────────────────────────
// Cortex — Universal AI Context Engine
// Copyright (c) 2026 Phani Marupaka. All rights reserved.
// Created & Developed by Phani Marupaka (https://linkedin.com/in/phani-marupaka)
// Licensed under MIT — see LICENSE for terms. Attribution required.
// ─────────────────────────────────────────────────────────────────────────────
/**
 * cortex import — Reverse-import existing provider files into .cortex/.
 *
 * If a project already has CLAUDE.md, .cursorrules, copilot-instructions.md etc.,
 * this command reads them and creates .cortex/rules/imported-{provider}.md files
 * so everything is centralized. This is the "onboarding" command.
 */

import { join, basename } from 'node:path';
import { existsSync, readFileSync } from 'node:fs';
import { findProjectRoot, getCortexDir, writeFileSafe } from '../utils/fs.js';
import { heading, info, warn, success, dim, error, fileCreated } from '../utils/log.js';

const PROVIDER_FILES = [
  { path: 'CLAUDE.md', provider: 'claude', name: 'Claude Code' },
  { path: '.cursorrules', provider: 'cursor', name: 'Cursor' },
  { path: '.github/copilot-instructions.md', provider: 'copilot', name: 'GitHub Copilot' },
  { path: '.windsurfrules', provider: 'windsurf', name: 'Windsurf' },
  { path: 'AGENTS.md', provider: 'codex', name: 'OpenAI Codex CLI' },
  { path: '.antigravity/instructions.md', provider: 'antigravity', name: 'Antigravity' },
  { path: '.gemini/style-guide.md', provider: 'gemini', name: 'Google Gemini' },
  { path: '.openai/instructions.md', provider: 'openai', name: 'OpenAI' },
];

export default async function importCmd({ values }) {
  const projectRoot = findProjectRoot();
  const cortexDir = getCortexDir(projectRoot);
  const dry = values.dry;
  const force = values.force;

  if (!existsSync(cortexDir)) {
    error('.cortex/ not found. Run `cortex init` first.');
    process.exit(1);
  }

  heading('Importing existing provider files');

  let imported = 0;
  let skipped = 0;

  for (const { path, provider, name } of PROVIDER_FILES) {
    const fullPath = join(projectRoot, path);
    if (!existsSync(fullPath)) continue;

    const content = readFileSync(fullPath, 'utf-8');

    // Skip files we generated ourselves
    if (content.includes('Auto-generated by cortex') && !force) {
      dim(`  ${name} (${path}) — skipped (auto-generated by cortex, use --force to override)`);
      skipped++;
      continue;
    }

    // Extract meaningful rules from the file
    const rules = extractRules(content);

    if (rules.length === 0) {
      dim(`  ${name} (${path}) — no extractable rules found`);
      continue;
    }

    info(`  ${name} (${path}) — found ${rules.length} rule(s)`);

    const destPath = join(cortexDir, 'rules', `imported-${provider}.md`);

    if (existsSync(destPath) && !force) {
      warn(`    ${destPath} already exists. Use --force to overwrite.`);
      skipped++;
      continue;
    }

    let output = `# Imported from ${name}\n`;
    output += `# Source: ${path}\n`;
    output += `# Imported by \`cortex import\` — review and edit as needed.\n\n`;

    // Group rules by likely category
    const categorized = categorizeRules(rules);
    for (const [category, items] of Object.entries(categorized)) {
      output += `## ${capitalize(category)}\n`;
      for (const item of items) {
        output += `- ${item}\n`;
      }
      output += '\n';
    }

    if (!dry) {
      writeFileSafe(destPath, output, { force: true });
      fileCreated(destPath);
    } else {
      dim(`    Would write ${destPath}`);
      for (const rule of rules.slice(0, 5)) {
        dim(`      - ${rule}`);
      }
      if (rules.length > 5) dim(`      ... and ${rules.length - 5} more`);
    }

    imported++;
  }

  console.log();
  if (imported > 0) {
    success(`Imported rules from ${imported} provider file(s)${skipped > 0 ? `, ${skipped} skipped` : ''}`);
    dim('Review imported rules in .cortex/rules/imported-*.md');
    dim('Run `cortex compile` to propagate to all providers.');
  } else if (skipped > 0) {
    info(`No new imports. ${skipped} file(s) skipped (already imported or auto-generated).`);
  } else {
    info('No existing provider files found to import.');
    dim('Provider files checked: CLAUDE.md, .cursorrules, copilot-instructions.md, etc.');
  }
}

/**
 * Extract meaningful rules/instructions from markdown content.
 */
function extractRules(content) {
  const rules = [];
  const lines = content.split('\n');

  for (const line of lines) {
    const trimmed = line.trim();

    // Skip headers, blank lines, metadata
    if (!trimmed || trimmed.startsWith('#') || trimmed.startsWith('>') || trimmed.startsWith('---')) continue;

    // Extract bullet points that look like rules
    if (trimmed.startsWith('- ') && trimmed.length > 15 && trimmed.length < 300) {
      const rule = trimmed.slice(2).trim();
      // Skip links, auto-generated markers, and metadata
      if (/^\[|^http|^Auto-generated|^Source:|^Imported by/.test(rule)) continue;
      rules.push(rule);
      continue;
    }

    // Extract numbered list items
    if (/^\d+\.\s/.test(trimmed) && trimmed.length > 15 && trimmed.length < 300) {
      const rule = trimmed.replace(/^\d+\.\s*/, '').trim();
      if (rule.length > 10) rules.push(rule);
      continue;
    }

    // Extract standalone instruction-like sentences
    if (trimmed.length > 20 && trimmed.length < 200 && !trimmed.includes('|') &&
        /^[A-Z]/.test(trimmed) && (trimmed.endsWith('.') || trimmed.endsWith(':'))) {
      rules.push(trimmed);
    }
  }

  return rules;
}

/**
 * Heuristic categorization of rules.
 */
function categorizeRules(rules) {
  const categories = {};
  const keywords = {
    style: ['format', 'indent', 'semicolon', 'quote', 'naming', 'camel', 'snake', 'style', 'concise', 'verbose', 'comment'],
    testing: ['test', 'spec', 'vitest', 'jest', 'mocha', 'coverage', 'assert'],
    language: ['typescript', 'javascript', 'python', 'rust', 'go', 'type', 'strict'],
    framework: ['react', 'next', 'vue', 'svelte', 'angular', 'express', 'fastapi', 'tailwind'],
    tooling: ['eslint', 'prettier', 'pnpm', 'yarn', 'npm', 'bun', 'docker', 'ci'],
    conventions: ['commit', 'branch', 'pr', 'review', 'merge', 'conventional'],
  };

  for (const rule of rules) {
    const lower = rule.toLowerCase();
    let placed = false;
    for (const [cat, words] of Object.entries(keywords)) {
      if (words.some(w => lower.includes(w))) {
        if (!categories[cat]) categories[cat] = [];
        categories[cat].push(rule);
        placed = true;
        break;
      }
    }
    if (!placed) {
      if (!categories.general) categories.general = [];
      categories.general.push(rule);
    }
  }

  return categories;
}

function capitalize(str) {
  return str.charAt(0).toUpperCase() + str.slice(1);
}
