// ─────────────────────────────────────────────────────────────────────────────
// Cortex — Universal AI Context Engine
// Copyright (c) 2026 Phani Marupaka. All rights reserved.
// Created & Developed by Phani Marupaka (https://linkedin.com/in/phani-marupaka)
// Licensed under MIT — see LICENSE for terms. Attribution required.
// ─────────────────────────────────────────────────────────────────────────────
/**
 * Metrics & Summary Engine — quantifies everything cortex does.
 *
 * Tracks:
 * - Time saved (manual config vs cortex compile)
 * - Token efficiency (how much context budget we use effectively)
 * - Rule evolution (how instructions improve over time)
 * - Provider coverage (how many tools are configured)
 * - Learning velocity (signals captured per session)
 *
 * Generates end-of-project summaries with hard numbers.
 */

import { loadSession } from './session.js';
import { loadConfig } from './config.js';
import { PROVIDER_SPECS } from './specs.js';
import { existsSync, readdirSync } from 'node:fs';
import { join } from 'node:path';
import { getCortexDir } from '../utils/fs.js';

// ── Time Estimates (minutes) ────────────────────────────────────────────────
// Rough per-event estimates of manual effort. Savings are only ever computed
// from events actually recorded in .cortex/session.json, and are always
// presented as estimates.

const MANUAL_ESTIMATES = {
  updateOneFile: 3,           // Hand-editing one provider file for a rule change
  writeOneRule: 2,            // Distilling one learned rule by hand
  reviewSignalBatch: 5,       // Auditing ~5 feedback signals by hand
};

const CORTEX_ESTIMATES = {
  updateOneFile: 0,           // Covered by the compile itself
  writeOneRule: 0,
  reviewSignalBatch: 0,
};

/**
 * Calculate what cortex has (approximately) saved for a project, based only on
 * recorded events: files generated by compiles, rules evolved and signals
 * captured by `cortex learn`.
 */
export function calculateSavings(projectRoot) {
  const session = loadSession(projectRoot);
  const config = loadConfig(projectRoot);
  const m = { ...session.metrics };
  for (const key of ['compilations', 'filesGenerated', 'signalsCaptured', 'rulesEvolved']) {
    m[key] = Number(m[key]) || 0;
  }

  const enabledProviders = Object.entries(config.providers || {})
    .filter(([, v]) => v).map(([k]) => k);

  const providerCount = enabledProviders.length;

  // Estimated time savings — zero unless events were recorded
  const updateSaved = m.filesGenerated * (MANUAL_ESTIMATES.updateOneFile - CORTEX_ESTIMATES.updateOneFile);
  const learnSaved =
    m.rulesEvolved * (MANUAL_ESTIMATES.writeOneRule - CORTEX_ESTIMATES.writeOneRule) +
    Math.ceil(m.signalsCaptured / 5) * (MANUAL_ESTIMATES.reviewSignalBatch - CORTEX_ESTIMATES.reviewSignalBatch);
  const setupSaved = 0;

  const totalTimeSavedMinutes = updateSaved + learnSaved;

  // Consistency score (0-100)
  const consistencyScore = Math.min(100, Math.round(
    (providerCount / Object.keys(PROVIDER_SPECS).length) * 40 +
    (m.compilations > 0 ? 30 : 0) +
    (m.rulesEvolved > 0 ? 20 : 0) +
    (m.signalsCaptured > 0 ? 10 : 0)
  ));

  // Learning velocity
  const daysSinceStart = session.startedAt
    ? Math.max(1, (Date.now() - new Date(session.startedAt).getTime()) / (1000 * 60 * 60 * 24))
    : 1;
  const signalsPerDay = m.signalsCaptured / daysSinceStart;

  return {
    time: {
      estimate: true,
      setupSavedMinutes: Math.round(setupSaved),
      updateSavedMinutes: Math.round(updateSaved),
      learnSavedMinutes: Math.round(learnSaved),
      totalSavedMinutes: Math.round(totalTimeSavedMinutes),
      totalSavedHours: +(totalTimeSavedMinutes / 60).toFixed(1),
    },
    coverage: {
      enabledProviders: providerCount,
      totalProviders: Object.keys(PROVIDER_SPECS).length,
      coveragePercent: Math.round((providerCount / Object.keys(PROVIDER_SPECS).length) * 100),
    },
    quality: {
      consistencyScore,
      rulesEvolved: m.rulesEvolved,
      signalsCaptured: m.signalsCaptured,
      signalsPerDay: +signalsPerDay.toFixed(1),
    },
    activity: {
      compilations: m.compilations,
      filesGenerated: m.filesGenerated,
      interactions: session.interactions,
      decisions: session.decisions.length,
      daysSinceStart: Math.round(daysSinceStart),
    },
  };
}

/**
 * Generate a full summary report (end-of-project or on-demand).
 */
export function generateSummary(projectRoot) {
  const savings = calculateSavings(projectRoot);
  const session = loadSession(projectRoot);
  const config = loadConfig(projectRoot);
  const cortexDir = getCortexDir(projectRoot);

  const rulesCount = countFiles(join(cortexDir, 'rules'));
  const skillsCount = countFiles(join(cortexDir, 'skills'));

  const lines = [];

  lines.push('╔══════════════════════════════════════════════════════════════╗');
  lines.push('║        Cortex — Project Summary                              ║');
  lines.push('║  Created by Phani Marupaka                                    ║');
  lines.push('║  https://github.com/Phani3108/Cortex                          ║');
  lines.push('╚══════════════════════════════════════════════════════════════╝');
  lines.push('');

  // Time savings
  lines.push('⏱  TIME SAVINGS (estimate, from recorded activity)');
  lines.push(`   Provider file updates: ~${savings.time.updateSavedMinutes} min (${savings.activity.filesGenerated} files generated)`);
  lines.push(`   Learning:              ~${savings.time.learnSavedMinutes} min (${savings.quality.rulesEvolved} rules evolved)`);
  lines.push(`   ─────────────────────────────`);
  lines.push(`   Estimated total:       ~${savings.time.totalSavedMinutes} min (${savings.time.totalSavedHours} hrs)`);
  lines.push('');

  // Coverage
  lines.push('🎯 PROVIDER COVERAGE');
  lines.push(`   Providers configured:  ${savings.coverage.enabledProviders} / ${savings.coverage.totalProviders}`);
  lines.push(`   Coverage:              ${savings.coverage.coveragePercent}%`);
  lines.push(`   Files generated:       ${savings.activity.filesGenerated}`);
  lines.push('');

  // Quality
  lines.push('📊 QUALITY METRICS');
  lines.push(`   Consistency score:     ${savings.quality.consistencyScore}/100`);
  lines.push(`   Rules:                 ${rulesCount} active`);
  lines.push(`   Skills:                ${skillsCount} loaded`);
  lines.push(`   Signals captured:      ${savings.quality.signalsCaptured}`);
  lines.push(`   Rules evolved:         ${savings.quality.rulesEvolved}`);
  lines.push(`   Learning velocity:     ${savings.quality.signalsPerDay} signals/day`);
  lines.push('');

  // Activity
  lines.push('📈 ACTIVITY');
  lines.push(`   Compilations:          ${savings.activity.compilations}`);
  lines.push(`   Interactions:          ${savings.activity.interactions}`);
  lines.push(`   Decisions recorded:    ${savings.activity.decisions}`);
  lines.push(`   Days active:           ${savings.activity.daysSinceStart}`);
  lines.push('');

  // Impact statement
  if (savings.time.totalSavedMinutes > 0) {
    lines.push('💡 IMPACT');
    lines.push(`   Keeping ${savings.activity.filesGenerated} generated file(s) in sync by hand would have`);
    lines.push(`   cost an estimated ~${savings.time.totalSavedMinutes} minutes of configuration work.`);
    if (savings.quality.signalsCaptured > 0) {
      lines.push(`   ${savings.quality.signalsCaptured} feedback signals were automatically captured and`);
      lines.push(`   distilled into ${savings.quality.rulesEvolved} rule improvements.`);
    }
  }

  return lines.join('\n');
}

function countFiles(dir) {
  if (!existsSync(dir)) return 0;
  return readdirSync(dir).filter(f => !f.startsWith('.')).length;
}

export { MANUAL_ESTIMATES, CORTEX_ESTIMATES };
