// ─────────────────────────────────────────────────────────────────────────────
// Cortex — Universal AI Context Engine
// Copyright (c) 2026 Phani Marupaka. All rights reserved.
// Created & Developed by Phani Marupaka (https://linkedin.com/in/phani-marupaka)
// Licensed under MIT — see LICENSE for terms. Attribution required.
// ─────────────────────────────────────────────────────────────────────────────
/**
 * Output planning — decides what `cortex compile` may write or delete.
 * Shared by compile, verify, status and diff.
 */

import { join, dirname } from 'node:path';
import { existsSync, readFileSync, readdirSync, rmdirSync } from 'node:fs';
import { hashContent, manifestEntry } from './manifest.js';
import { isGenerated, LEGACY_OUTPUTS } from '../engine/index.js';

/**
 * Decide, per output, whether to create / update / leave / refuse.
 * Refuses to overwrite files Cortex did not generate, and generated files a
 * human edited since the last compile (unless --force).
 */
export function planWrites(projectRoot, outputs, manifest, { force = false } = {}) {
  return outputs.map(output => {
    const abs = join(projectRoot, output.path);
    const base = { file: output.path, abs, output };
    if (!existsSync(abs)) return { ...base, action: 'create' };
    const current = readFileSync(abs, 'utf-8');
    if (current === output.content) return { ...base, action: 'unchanged' };
    if (force) return { ...base, action: 'update' };
    if (!isGenerated(current)) return { ...base, action: 'conflict', reason: 'hand-written file (not generated by Cortex)' };
    const entry = manifestEntry(manifest, output.path);
    if (entry && hashContent(current) !== entry.hash) return { ...base, action: 'conflict', reason: 'edited by hand since the last compile' };
    return { ...base, action: 'update' };
  });
}

/**
 * Files Cortex produced before but no longer produces (renamed skills,
 * disabled targets, legacy paths from Cortex v1). Deleted only when they are
 * untouched since generation.
 */
export function planRemovals(projectRoot, outputs, manifest, compiledTargets) {
  const current = new Set(outputs.map(o => o.path));
  const recompiled = new Set(compiledTargets);
  const out = [];
  const seen = new Set();

  for (const entry of manifest?.files || []) {
    if (current.has(entry.file) || seen.has(entry.file)) continue;
    const owners = entry.targets || [entry.provider];
    if (!owners.some(t => recompiled.has(t))) continue;
    seen.add(entry.file);
    const abs = join(projectRoot, entry.file);
    if (!existsSync(abs)) continue;
    const content = readFileSync(abs, 'utf-8');
    const pristine = hashContent(content) === entry.hash;
    out.push(pristine
      ? { file: entry.file, abs, action: 'delete', reason: 'no longer generated' }
      : { file: entry.file, abs, action: 'keep', reason: 'no longer generated, but edited by hand' });
  }

  for (const file of LEGACY_OUTPUTS) {
    if (current.has(file) || seen.has(file)) continue;
    const abs = join(projectRoot, file);
    if (!existsSync(abs)) continue;
    const content = readFileSync(abs, 'utf-8');
    if (isGenerated(content) || isLegacySettings(file, content)) {
      out.push({ file, abs, action: 'delete', reason: 'legacy Cortex v1 output' });
    }
  }
  return out;
}

/** Cortex v1 wrote invalid settings files with no marker; recognise them by shape. */
function isLegacySettings(file, content) {
  if (!file.endsWith('settings.json')) return false;
  try {
    const obj = JSON.parse(content);
    const keys = Object.keys(obj).sort().join(',');
    if (file === '.claude/settings.json') {
      return ['memory,permissions', 'ignorePaths,memory,permissions'].includes(keys) && !Object.keys(obj.permissions || {}).length;
    }
    if (file === '.gemini/settings.json') {
      return ['codeStyle,sandbox', 'codeStyle,ignorePaths,sandbox'].includes(keys);
    }
  } catch { /* not JSON */ }
  return false;
}

export function pruneEmptyDirs(dir, stopAt) {
  let d = dir;
  while (d.startsWith(stopAt) && d !== stopAt) {
    try {
      if (readdirSync(d).length) break;
      rmdirSync(d);
    } catch { break; }
    d = dirname(d);
  }
}

