// CLI: init → import → compile safety, --check drift detection, v1 cleanup.
import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, writeFileSync, readFileSync, existsSync, mkdirSync, appendFileSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { spawnSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';

const BIN = fileURLToPath(new URL('../../bin/cortex.js', import.meta.url));

function project(files = {}) {
  const dir = mkdtempSync(join(tmpdir(), 'cortex-cli-'));
  const home = mkdtempSync(join(tmpdir(), 'cortex-home-'));
  spawnSync('git', ['init', '-q'], { cwd: dir });
  for (const [p, c] of Object.entries(files)) {
    mkdirSync(join(dir, p, '..'), { recursive: true });
    writeFileSync(join(dir, p), c);
  }
  const run = (...args) => spawnSync(process.execPath, [BIN, ...args], { cwd: dir, env: { ...process.env, HOME: home, CORTEX_HOME: join(home, '.cortex'), NO_COLOR: '1' }, encoding: 'utf-8' });
  return { dir, run, read: p => readFileSync(join(dir, p), 'utf-8'), has: p => existsSync(join(dir, p)) };
}

test('init detects tools + TypeScript and imports hand-written files', () => {
  const p = project({
    'package.json': JSON.stringify({ name: 'app', devDependencies: { typescript: '5' } }),
    'CLAUDE.md': '# Mine\n## Style\n- Use tabs\n',
  });
  const r = p.run('init');
  assert.equal(r.status, 0, r.stderr);
  const cfg = p.read('.cortex/config.yaml');
  assert.match(cfg, /language: TypeScript/);
  assert.match(cfg, /claude: true/);
  assert.match(cfg, /codex: true/);
  assert.match(p.read('.cortex/rules/imported-claude.md'), /- Use tabs/);
});

test('compile never overwrites a hand-written file without --force', () => {
  const p = project({ 'package.json': '{}', 'CLAUDE.md': '# Hand written\n- keep me\n' });
  p.run('init');
  const r = p.run('compile');
  assert.equal(r.status, 1);
  assert.match(r.stdout + r.stderr, /hand-written/);
  assert.equal(p.read('CLAUDE.md'), '# Hand written\n- keep me\n');
  assert.equal(p.run('compile', '--force').status, 0);
  assert.match(p.read('CLAUDE.md'), /Generated by Cortex/);
  assert.match(p.read('CLAUDE.md'), /keep me/, 'imported rule survives in generated output');
});

test('--check passes when current and fails on drift or hand edits', () => {
  const p = project({ 'package.json': '{}' });
  p.run('init');
  assert.equal(p.run('compile').status, 0);
  assert.equal(p.run('compile', '--check').status, 0);
  appendFileSync(join(p.dir, '.cortex/rules/project.md'), '\n- A brand new rule\n');
  assert.equal(p.run('compile', '--check').status, 1);
  assert.equal(p.run('compile').status, 0);
  appendFileSync(join(p.dir, 'AGENTS.md'), '\n- sneaky edit\n');
  assert.equal(p.run('compile', '--check').status, 1);
  const r = p.run('compile');
  assert.equal(r.status, 1, 'hand-edited generated file is skipped');
  assert.match(p.read('AGENTS.md'), /sneaky edit/);
});

test('files no longer generated are removed; legacy v1 outputs are cleaned up', () => {
  const p = project({
    'package.json': '{}',
    '.cursorrules': '# Cursor Rules — Auto-generated by [Cortex](https://github.com/Phani3108/Cortex)\n- old\n',
    '.claude/settings.json': JSON.stringify({ permissions: {}, memory: { enabled: true }, ignorePaths: ['dist'] }),
  });
  mkdirSync(join(p.dir, '.cortex/skills'), { recursive: true });
  p.run('init');
  writeFileSync(join(p.dir, '.cortex/skills/review.md'), '---\nname: review\ndescription: Review diffs\n---\nSteps');
  assert.equal(p.run('compile', '--force').status, 0);
  assert.ok(!p.has('.cursorrules'), 'v1 .cursorrules removed');
  assert.ok(!p.has('.claude/settings.json'), 'v1 invalid settings removed');
  assert.ok(p.has('.claude/skills/review/SKILL.md'));
  spawnSync('rm', [join(p.dir, '.cortex/skills/review.md')]);
  assert.equal(p.run('compile').status, 0);
  assert.ok(!p.has('.claude/skills/review/SKILL.md'), 'stale skill removed');
});

test('a user settings.json is never deleted', () => {
  const p = project({ 'package.json': '{}', '.claude/settings.json': JSON.stringify({ permissions: { allow: ['Bash(npm test)'] } }) });
  p.run('init');
  p.run('compile', '--force');
  assert.ok(p.has('.claude/settings.json'));
});

test('import skips Cortex-generated files and is idempotent', () => {
  const p = project({ 'package.json': '{}' });
  p.run('init');
  p.run('compile');
  const r = p.run('import');
  assert.match(r.stdout, /generated by Cortex, skipped/);
  assert.ok(!existsSync(join(p.dir, '.cortex/rules/imported-claude.md')));
});

test('unknown command and flag exit 2 with a hint', () => {
  const p = project();
  assert.equal(p.run('compil').status, 2);
  assert.equal(p.run('status', '--nope').status, 2);
});
