import { test } from 'node:test';
import assert from 'node:assert/strict';
import {
  captureSignals, CONVENTIONAL_COMMIT, TEST_WORD, extractMeaningfulDiff, stripListMarker,
} from '../../src/core/signals.js';
import { gitRepo, git, tempDir, write } from './helpers.js';

test('conventional commit regex requires the full prefix', () => {
  for (const ok of ['feat: add x', 'fix(api): y', 'refactor!: z', 'revert: a', 'chore(deps)!: bump']) {
    assert.ok(CONVENTIONAL_COMMIT.test(ok), ok);
  }
  for (const bad of ['feature: add', 'fixed the bug', 'Fix: capital', 'docs update', 'test stuff', 'feat add']) {
    assert.ok(!CONVENTIONAL_COMMIT.test(bad), bad);
  }
});

test('test-culture word match uses word boundaries', () => {
  assert.ok(TEST_WORD.test('add tests for parser'));
  assert.ok(TEST_WORD.test('update spec'));
  assert.ok(!TEST_WORD.test('bump to latest'));
  assert.ok(!TEST_WORD.test('attestation fix'));
  assert.ok(!TEST_WORD.test('respect config'));
});

test('git signals: conventional commits detected, "latest" is not testing culture', () => {
  const repo = gitRepo();
  const msgs = ['feat: a', 'fix: b', 'chore: update to latest', 'feat(x): c', 'docs: latest readme'];
  for (const m of msgs) git(repo, 'commit', '-q', '--allow-empty', '-m', m);
  const contents = captureSignals(repo).signals.map(s => s.content);
  assert.ok(contents.some(c => /conventional commits/.test(c)));
  assert.ok(!contents.some(c => /testing culture/.test(c)));
});

test('non-conventional history yields no conventional-commit signal', () => {
  const repo = gitRepo();
  for (const m of ['feature: a', 'fixed b', 'fixup c']) git(repo, 'commit', '-q', '--allow-empty', '-m', m);
  const contents = captureSignals(repo).signals.map(s => s.content);
  assert.ok(!contents.some(c => /conventional commits/.test(c)));
});

test('JS style rules only come from JS/TS files', () => {
  const root = tempDir();
  // Python file full of lines without semicolons and with double quotes
  const py = Array.from({ length: 60 }, (_, i) => `value_${i} = "string number ${i}"`).join('\n');
  write(root, 'src/app.py', py);
  const contents = captureSignals(root).signals.map(s => s.content);
  assert.ok(!contents.some(c => /semicolon/i.test(c)), 'no semicolon rule from Python');
  assert.ok(!contents.some(c => /quotes for strings/i.test(c)), 'no quote rule from Python');
  assert.ok(!contents.some(c => /\bvar\b|Prefer const/.test(c)));
});

test('JS files still produce semicolon rules', () => {
  const root = tempDir();
  const js = Array.from({ length: 60 }, (_, i) => `const value${i} = 'string number ${i}';`).join('\n');
  write(root, 'src/app.js', js);
  const contents = captureSignals(root).signals.map(s => s.content);
  assert.ok(contents.some(c => /Use semicolons/.test(c)));
});

test('diff lines are stripped of list markers', () => {
  const diff = extractMeaningfulDiff('# T\n- Old rule that was here\n', '# T\n- - New rule added by the user\n');
  assert.deepEqual(diff.added, ['New rule added by the user']);
  assert.deepEqual(diff.removed, ['Old rule that was here']);
  assert.equal(stripListMarker('1. - [x] done item'), 'done item');
});

test('files marked "Generated by Cortex" are not re-imported', () => {
  const root = tempDir();
  write(root, 'CLAUDE.md', '<!-- Generated by Cortex -->\n- A rule that came from cortex itself\n');
  write(root, 'AGENTS.md', '# Mine\n- A rule the user wrote by hand here\n');
  const imported = captureSignals(root).signals.filter(s => s.action === 'import_as_rule').map(s => s.source);
  assert.deepEqual(imported, ['AGENTS.md']);
});

test('edits to compiled files become signals via the manifest', () => {
  const root = tempDir();
  const compiled = '# Rules\n- Original compiled rule text\n';
  write(root, 'CLAUDE.md', compiled + '- A brand new user rule line\n');
  write(root, '.cortex/.compile-manifest.json', JSON.stringify({
    version: 2,
    files: [{ file: 'CLAUDE.md', path: '/somewhere/else/CLAUDE.md', targets: ['claude'], compiledContent: compiled }],
  }));
  const edits = captureSignals(root).signals.filter(s => s.type === 'user_edit');
  assert.deepEqual(edits.map(e => e.content), ['A brand new user rule line']);
});
